runtime: go113

# Update with Redis instance details
env_variables:
  REDISHOST: '10.166.68.59'
  REDISPORT: '6379'

# Update with Serverless VPC Access connector details
vpc_access_connector:
  name: 'projects/sinmetal-lab/locations/asia-northeast1/connectors/test1'
# [END memorystore_go_app_yaml_standard]