runtime: go113

# Update with Redis instance details
env_variables:
  REDISHOST: '10.49.212.99'
  REDISPORT: '6379'

# Update with Serverless VPC Access connector details
vpc_access_connector:
  name: 'projects/sinmetal-lab-us/locations/us-central1/connectors/test1'
# [END memorystore_go_app_yaml_standard]